version: "3"

services:
  nest-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - .:/app
    networks:
        - nest_network
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80" 
    environment:
      - PGADMIN_DEFAULT_EMAIL=nest@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - nest_network
      
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=nest_db
    networks:
      nest_network:
            ipv4_address: 172.11.0.2


networks:
  nest_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16
          gateway: 172.11.0.1